name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'
        
    - name: Get version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
        
    - name: Build
      run: |
        mkdir -p build
        go build -o build/WinCuts.exe -ldflags "-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}"
        cp default_config.yaml build/default_config.yaml
        echo "Build contents:"
        ls -la build/
        echo "Testing version:"
        ./build/WinCuts.exe -v || true
      env:
        GOOS: windows
        GOARCH: amd64
        
    - name: Create archive
      run: |
        cd build
        echo "Creating archive with:"
        ls -la
        zip WinCuts-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip WinCuts.exe default_config.yaml
        echo "Archive contents:"
        unzip -l WinCuts-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/WinCuts-*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Installation
          Open PowerShell and run:
          ```powershell
          irm https://raw.githubusercontent.com/fingann/WinCuts/main/install.ps1 | iex
          ```
