name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'
        
    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash
        
    - name: Build
      run: |
        mkdir build
        go build -o build/WinCuts.exe -ldflags "-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}"
      env:
        GOOS: windows
        GOARCH: amd64
        
    - name: Create archive
      run: |
        Compress-Archive -Path "build/WinCuts.exe", "README.md", "default_config.yaml" -DestinationPath "build/WinCuts-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip" -Force
      shell: pwsh
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/WinCuts-*.zip
        draft: false
        prerelease: false
        generate_release_notes: true 