name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'
        
    - name: Get version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
        
    - name: Build
      run: |
        mkdir -p build/WinCuts
        go build -o build/WinCuts/WinCuts.exe -ldflags "-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}"
        cp config/default_config.yaml build/WinCuts/default_config.yaml
        ls -la build/WinCuts/
        ./build/WinCuts/WinCuts.exe -v || true
      env:
        GOOS: windows
        GOARCH: amd64
        
    - name: Create archive
      run: |
        cd build
        zip -r WinCuts-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip WinCuts/
        unzip -l WinCuts-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/WinCuts-*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Installation
          See [INSTALL.md](INSTALL.md) for detailed installation instructions.

          ## Quick Install (Recommended)
          Open PowerShell and run:
          ```powershell
          irm https://raw.githubusercontent.com/fingann/WinCuts/main/install.ps1 | iex
          ```
